#pragma once

#include "visibilityangledifferencetoglobalhorizon.h"
#include "visibilityangledifferencetolocalhorizon.h"
#include "visibilityboolean.h"
#include "visibilitydistanceglobalhorizon.h"
#include "visibilitydistancelocalhorizon.h"
#include "visibilityelevationdifference.h"
#include "visibilityelevationdifferencetoglobalhorizon.h"
#include "visibilityelevationdifferencetolocalhorizon.h"
#include "visibilityfuzzy.h"
#include "visibilityhorizons.h"
#include "visibilityhorizonscount.h"
#include "visibilityslopetoviewangle.h"
#include "visibilityviewangle.h"