#ifndef TEST_SETTINGS_H_IN
#define TEST_SETTINGS_H_IN

#define TEST_DATA_DIR "@TEST_DATA_DIR@"
#define TEST_DATA_RESULTS_DIR "@TEST_DATA_DIR@/results"
#define TEST_DATA_DSM "@TEST_DATA_DIR@/dsm.tif"
#define TEST_DATA_LOS "@TEST_DATA_DIR@/los.csv"

#endif // TEST_SETTINGS_H_IN