package:
  name: libviewshed
  version: "4.1.2"

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pthread-stubs
    - libgdal
    - libsimplerasters
    - qt-main 5.*
    - mesalib # [unix]
  host:
    - pthread-stubs
    - libgdal
    - libsimplerasters
    - qt-main 5.*
    - mesalib # [unix]
  run:
    - libgdal
    - libsimplerasters
    - qt-main 5.*
    - mesalib # [unix]

test:
  files:
    - test_script.sh  # [unix]
    - test_script.bat  # [win]
  commands:
    - bash test_script.sh  # [unix]
    - call test_script.bat  # [win]

about:
  home: https://github.com/JanCaha/cpp-viewshed-library
  license: MIT
  summary: "C++ Viewshed library based on GDAL and Qt"

extra:
  recipe-maintainers:
    - JanCaha
  channels:
    - https://jancaha.github.io/conda-channel/
    - conda-forge
    - defaults
