name: Tests for Library on Windows

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

env:
  COMPILER: cl

jobs:

  Tests-Viewshed-library:

    runs-on: windows-latest

    steps:

      - name: Setup Environment
        run: |
          choco install ninja cmake gdal -y
          choco install qt5 -y
          refreshenv

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Clone Dependency Library
        uses: actions/checkout@v4
        with:
          repository: JanCaha/cpp-simplerasters
          path: simplerasters

      - name: Build Dependency Library
        run: |
          mkdir simplerasters/build
          cmake -S simplerasters -B simplerasters/build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build simplerasters/build --config Release
          cmake --install simplerasters/build --prefix "C:/simplerasters"

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build -G Ninja ^
            -DCMAKE_CXX_COMPILER=${COMPILER} ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DPACK_DEB:bool=off ^
            -DBUILD_DOCUMENTATION:bool=off ^
            -DBUILD_TESTS:bool=on ^
            -DCELL_EVENT_DATA_FLOAT:bool=on ^
            -DOUTPUT_RASTER_DATA_FLOAT:bool=on ^
            -DNEEDS_QT:bool=off ^
            -DCMAKE_PREFIX_PATH="C:/simplerasters"

      - name: Build
        run: |
          cmake --build build --config Release --target library_viewshed

      - name: Run Tests
        run: |
          cmake --build build --config Release --target build_tests
          cmake --build build --config Release --target run_tests
