name: Download and Install

on: [push, pull_request]


        
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

        - uses: robinraju/release-downloader@v1.8
          with:
            repository: "JanCaha/cpp-simplerasters"
            latest: true
            fileName: "*.deb"
            tarBall: false
            zipBall: false
        
        - name: Print files
          run : ls -l    
          
        - name: Install and remove artifact
          run: |
            sudo apt install ./simplerasters*.deb
            rm simplerasters*
          
        - name: Print files
          run : ls -l    
