name: Release Docker Image

on:
  push:
    paths:
      - docker/**
      - .github/workflows/release_docker.yaml
    branches:
      - master
      - main
  workflow_run:
    workflows: ["Tests for Library"]
    types:
      - completed
    branches:
      - 'main'
      - 'master'

jobs:

  Release-Docker-Viewshed:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: create_deb_file.yaml
          repo: JanCaha/cpp-simplerasters
          branch: main
          name: _packages
          name_is_regexp: true

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: test_plugin.yaml
          workflow_conclusion: success
          name: _packages
          name_is_regexp: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare for docker build 
        run: |
          cd docker
          mkdir install
          cp ../_packages/viewshed_*.deb install/

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          context: docker/
          push: true
          tags: cahik/viewshed:latest

