name: Release to PPA

on:
  push

jobs:

  Relese-to-PPA:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGE: viewshed
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env
        run: echo "VERSION=$(grep "project("  CMakeLists.txt | grep -E -o -e "[0-9\.]+" | head -n 1)" >> $GITHUB_ENV
      
      - name: Print Version
        run: |
          echo "-----"
          echo "Project Version"
          echo ${PACKAGE}
          echo ${VERSION}
          echo "-----"

      - name: install build tools
        run: |
          sudo apt-get update
          sudo apt-get install debhelper devscripts dput
      
      - name: import gpg key 55C76CE00DD5C647
        run: |
          echo "${GPG_PRIVATE_KEY}" | base64 --decode | gpg --batch --quiet --import
          echo "${GPG_PASSPHRASE}" | gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -u 55C76CE00DD5C647 --dry-run --sign README.md
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: Create tar.gz package
        run: |
          cd ..
          dir
          tar -acf "${PACKAGE}"_"${VERSION}".orig.tar.gz cpp-viewshed-library
          ls -l

      - name: Debuild
        run: debuild -S -sa -d
        env:
          DEBSIGN_PROGRAM: gpg --batch --pinentry-mode loopback
          DEBSIGN_KEYID: 55C76CE00DD5C647
      
      - name: Show Files
        run: |
          cd ..
          ls -l

      - name: Dput to Repo
        run: |
          cd ..
          dput ppa:jancaha/gis-tools "${PACKAGE}"_"${VERSION}"-0ppa0_source.changes
