name: Release Docker Image

on:
  workflow_run:
    workflows: ["Tests for Library"]
    types:
      - completed
    # branches:
    #   - 'main'
    #   - 'master'

jobs:

  Release-Docker-Viewshed:

    runs-on: ubuntu-latest

    steps:

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: test_plugin.yaml
          workflow_conclusion: success
          name: viewshed_.+deb
          name_is_regexp: true
          path: _packages

      - name: Prepare for docker build
        run: |
          sudo cmake --build build --config Release --target pack_deb
          cd docker
          mkdir install
          cp ../_packages/viewshed_*.deb install/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: docker/Dockerfile
      #     context: docker/
      #     push: true
      #     tags: cahik/viewshed:latest
        