name: Tests for Library

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  Tests-Viewshed-library-linux:
    runs-on: ubuntu-26.04

    env:
      DEBIAN_FRONTEND: "noninteractive"
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build doxygen libgtest-dev libgmock-dev clang

      - name: Install GDAL
        run: |
          sudo apt update
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Install Qt
        run: |
          sudo apt-get install qt6-base-dev qt6-base-dev-tools

      - uses: actions/checkout@v6
        with:
          repository: "JanCaha/cpp-simplerasters"
          path: "cpp-simplerasters"

      - name: Install simplerasters
        run: |
          cd cpp-simplerasters
          sudo cmake --workflow --preset workflow-release-install
          cd ..
          sudo rm -rf cpp-simplerasters

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Test
        run: |
          cmake --workflow --preset workflow-debug-tests

      - name: Install
        run: |
          sudo cmake --workflow --preset workflow-release-install

  Tests-Viewshed-library-macos:
    runs-on: macos-latest

    env:
      QT_QPA_PLATFORM: "offscreen"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CMAKE_PREFIX_PATH: "/opt/homebrew/opt/qt@6"

    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install ninja doxygen googletest gdal qt@6

      - uses: actions/checkout@v6
        with:
          repository: "JanCaha/cpp-simplerasters"
          path: "cpp-simplerasters"

      - name: Install simplerasters
        run: |
          cd cpp-simplerasters
          sudo cmake --workflow --preset workflow-release-install
          cd ..
          sudo rm -rf cpp-simplerasters

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Test
        run: |
          cmake --workflow --preset workflow-debug-tests

      - name: Install
        run: |
          sudo cmake --workflow --preset workflow-release-install
