name: Tests for Library

on:
  push:
    branches-ignore:
      - "ex-**" 
      - "experiments**"
    paths:
      - src/**
      - include/**
      - external/** 
      - cmake/**
      - CMakeLists.txt
      -- **/CMakeLists.txt
      - .github/workflows/test_plugin.yaml

jobs:

  Tests-Viewshed-library:

    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: "noninteractive"
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Add Sources
        run: |
          sudo gpg -k
          sudo wget -qO /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] https://qgis.org/ubuntu `lsb_release -c -s` main" > /etc/apt/sources.list.d/qgis.list'
      
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build

      - name: Install QGIS
        run: |
          sudo apt -y install qgis qgis-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: | 
           mkdir build
           cmake \
             -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DPACK_DEB:bool=on \
            -DBUILD_DOCUMENTATION:bool=on \
            -DBUILD_TESTS:bool=on \
            -DCELL_EVENT_DATA_FLOAT:bool=on \
            -DOUTPUT_RASTER_DATA_FLOAT:bool=on

      - name: Build
        run: | 
           cmake --build build --config Release --target viewshed

      - name: Test install
        run: |
          sudo cmake --build build --config Release --target install

      - name: Run Tests
        id: unittests
        run: |
           cmake --build build --config Release --target build_tests
           cmake --build build --config Release --target run_tests

      - name: Clean Build
        run: |
          sudo cmake --build build --target clean

      - name: Run Tests with double
        id: unittestsdouble
        run: |
           cmake \
             -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DPACK_DEB:bool=off \
            -DBUILD_DOCUMENTATION:bool=off \
            -DBUILD_TESTS:bool=on \
            -DCELL_EVENT_DATA_FLOAT:bool=off \
            -DOUTPUT_RASTER_DATA_FLOAT:bool=off
           cmake --build build --config Release --target build_tests
           cmake --build build --config Release --target run_tests
