name: Tests for Library

on:
  push

jobs:

  Tests-Viewshed-library:

    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: "noninteractive"
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Add Sources
        run: |
          sudo gpg -k
          wget -qO - https://qgis.org/downloads/qgis-2022.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import || true
          sudo chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
          sudo add-apt-repository "deb https://qgis.org/ubuntu `lsb_release -c -s` main"
      
      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install QGIS
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt -y install qgis qgis-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure and Build
        run: | 
           mkdir build
           cd build
           cmake ..
           cmake --build .

      - name: Run Tests
        id: unittests
        run: | 
           cd build
           ctest
