name: Tests for Library

on:
  push:
    branches-ignore:
      - "ex-**" 
      - "experiments**"
    paths:
      - src/**
      - tests/**
      - include/**
      - external/** 
      - cmake/**
      - CMakeLists.txt
      - "**/CMakeLists.txt"
      - .github/workflows/test_plugin.yaml

jobs:

  Tests-Viewshed-library:

    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: "noninteractive"
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Update and Upgrade
        run: |
          sudo apt update
          sudo apt install ninja-build doxygen

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'

      - name: Install GDAL
        run: |
          sudo apt-get -y install gdal-bin libgdal-dev

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: create_deb_file.yaml
          repo: JanCaha/cpp-simplerasters
          branch: main
      
      - name: Install and remove artifact
        run: |
          sudo apt install ./_packages/simplerasters*.deb
          rm -rf _packages

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: | 
           mkdir build
           cmake \
             -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DPACK_DEB:bool=on \
            -DBUILD_DOCUMENTATION:bool=off \
            -DBUILD_TESTS:bool=on \
            -DCELL_EVENT_DATA_FLOAT:bool=on \
            -DOUTPUT_RASTER_DATA_FLOAT:bool=on

      - name: Build
        run: | 
           cmake --build build --config Release --target viewshed

      - name: Test install
        run: |
          sudo cmake --build build --config Release --target install

      - name: Run Tests
        id: unittests
        run: |
           cmake --build build --config Release --target build_tests
           cmake --build build --config Release --target run_tests

      - name: Clean Build
        run: |
          sudo cmake --build build --target clean

      - name: Run Tests with double
        id: unittestsdouble
        run: |
           cmake \
             -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DPACK_DEB:bool=off \
            -DBUILD_DOCUMENTATION:bool=off \
            -DBUILD_TESTS:bool=on \
            -DCELL_EVENT_DATA_FLOAT:bool=off \
            -DOUTPUT_RASTER_DATA_FLOAT:bool=off
           cmake --build build --config Release --target build_tests
           cmake --build build --config Release --target run_tests

      - name: Configure Packing DEB
        run: | 
          rm -rf build
          mkdir build
          mkdir documentation
          cmake \
            -S. \
            -Bbuild \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DPACK_DEB:bool=on \
            -DBUILD_DOCUMENTATION:bool=on \
            -DBUILD_TESTS:bool=off \
            -DCELL_EVENT_DATA_FLOAT:bool=on \
            -DOUTPUT_RASTER_DATA_FLOAT:bool=on
          
      - name: Build DEB
        run: | 
          cmake --build build --config Release --target all
          cmake --build build --config Release --target pack_viewshed_library_deb

      - name: Upload DEB file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: _packages
          path: _packages/viewshed_*.deb
      
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
          publish_branch: gh-pages 
