name: Test WF

on:
  push

jobs:

  Create-deb-file-library:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
  
        - name: Update and Upgrade
          run: |
            sudo apt update
            sudo apt install ninja-build

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '5.15.2'
            host: 'linux'
        
        - name: Install GDAL
          run: |
            sudo apt-get -y install gdal-bin libgdal-dev
        
        - name: Download artifact
          id: download-artifact
          uses: dawidd6/action-download-artifact@v2
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: create_deb_file.yaml
            repo: JanCaha/cpp-simplerasters
            branch: main
        
        - name: Install and remove artifact
          run: |
            sudo apt install ./_packages/simplerasters*.deb
            rm -rf _packages

        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure
          run: | 
            mkdir build
            cmake \
              -S. \
              -Bbuild \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DPACK_DEB:bool=on \
              -DBUILD_DOCUMENTATION:bool=on \
              -DBUILD_TESTS:bool=on \
              -DCELL_EVENT_DATA_FLOAT:bool=on \
              -DOUTPUT_RASTER_DATA_FLOAT:bool=on

        - name: Build DEB
          run: | 
            cmake --build build --config Release --target all
            cmake --build build --config Release --target pack_viewshed_library_deb

        - name: Upload DEB file as artifact
          uses: actions/upload-artifact@v3
          with:
            name: _packages
            path: _packages/viewshed_*.deb
        
        - name: Deploy Documentation
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./documentation
            publish_branch: gh-pages
    
  Relese-Docker:

    runs-on: ubuntu-latest

    needs: Create-deb-file-library

    steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: _packages
        
        - name: List Folders
          run: |
            ls -l

        - name: Prepare for docker build 
          run: |
            mkdir docker/install
            mv viewshed_*.deb docker/install/    

        - name: Download artifact
          id: download-artifact
          uses: dawidd6/action-download-artifact@v2
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: create_deb_file.yaml
            repo: JanCaha/cpp-simplerasters
            branch: main
        
        - name: Copy simplerasters to docker folder
          run: |
            mkdir docker/install
            mv _packages/simplerasters_*.deb docker/install/ 

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Copy viewshed to docker folder
          run: |
            cd docker
            cp ../_packages/viewshed_*.deb install/

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            file: docker/Dockerfile
            context: docker/
            push: true
            tags: cahik/viewshed:latest
